# Generated by Django 4.2 on 2025-07-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default/pfp.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
